# Database Credentials
db.driverName = com.mysql.cj.jdbc.Driver
db.connectionString = jdbc:mysql://localhost:3306/shopping-cart
db.username = root
db.password = Vardhan@12345

#Mailer Credentials
mailer.email=vardhanvenkata888@gmail.com
mailer.password=aanr aarr pfsc aoee